### ISSUE TITLE
object 'cumtrapzRcpp' not found

### ISSUE THREAD

**Issue by liamheng** [functionaldata/tDENS#1]
Error message when run:
x <- seq(0,2,length.out =512)
y <- rep(0.5,length.out =512)
yOnLQ <- dens2lqd(dens=y, dSup = x)

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'cumtrapzRcpp' not found

I installed tPACE, but still have this error.

**Comment by hadjipantelis** [comment]
Hello lihengbit (Heng),

Please provide `sessionInfo()` output and try reinstalling. 
I just typed `devtools::install_github("functionaldata/tDENS"); library(fdadensity);` and then tried the code you provided and it run without a problem. So I strongly suspect the issue is with your local installation. 

All the best,
Pantelis

**Comment by liamheng** [comment]
Pantelis,
Thank you.
According to your suggestion, I update my R. And it works with the new version.

Best,
Heng

**Comment by hadjipantelis** [comment]
Great! Best of luck with the rest of your analysis!
